# .github/workflows/flutter_package.yaml
name: flutter_package
on: pull_request

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      path: "./coverage/lcov.info"
      min_coverage: 80
