name: very_good_weather

on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Flutter action
        uses: subosito/flutter-action@v2.2.1
        with:
          channel: master

      - name: Install Dependencies
        run: flutter packages get

      - name: Analyze
        run: flutter analyze lib test

      - name: simple-cspell
        uses: zwaldowski/cspell-action@1.0.0
      
      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
